DELIMITER @@
CREATE PROCEDURE validarUsuario(IN USUARIO VARCHAR(45))
BEGIN
    SELECT * FROM USUARIO WHERE USER=USUARIO;
END @@
DELIMITER;

DELIMITER @@
CREATE PROCEDURE insertarCliente(IN USUARIO VARCHAR(45),
                                 IN PASS VARCHAR(255),IN RUT VARCHAR(45),IN NOMBRE VARCHAR(45),IN APELLIDO VARCHAR(45),
                                 IN DIRECCION VARCHAR(100),IN EMAIL VARCHAR(100),IN TELEFONO VARCHAR(45))
BEGIN
    INSERT INTO USUARIO VALUES(USUARIO,PASS,'Cliente','SI');
    INSERT INTO CLIENTE VALUES(RUT,NOMBRE,APELLIDO,DIRECCION,EMAIL,TELEFONO,USUARIO);
END @@
DELIMITER ;

DELIMITER @@
CREATE PROCEDURE insertarProducto(IN NOMBRE VARCHAR(45),IN TIPOBICI VARCHAR(45),IN ARO INT,IN MARCA VARCHAR(45),IN MODELO VARCHAR(45),IN PRECIO INT,
                                  IN PROMOCION INT,IN STOCK INT,IN FOTO VARCHAR(45),IN RUT_CLI VARCHAR(45),IN RUT_EMP VARCHAR(45))
BEGIN
    INSERT INTO PRODUCTO VALUES(NULL,NOMBRE,TIPOBICI,ARO,MARCA,MODELO,PRECIO,NOW(),PROMOCION,STOCK,'NO',FOTO,RUT_CLI,RUT_EMP);
END @@
DELIMITER;

----------------------------------
DELIMITER @@
CREATE PROCEDURE insertarCliente(IN RUT VARCHAR(45),IN NOMBRE VARCHAR(45),IN APELLIDO VARCHAR(45),
                                 IN DIRECCION VARCHAR(100),IN EMAIL VARCHAR(100),IN TELEFONO VARCHAR(45),IN USUARIO VARCHAR(45))
BEGIN
     INSERT INTO CLIENTE VALUES(RUT,NOMBRE,APELLIDO,DIRECCION,EMAIL,TELEFONO,USUARIO);
END @@
DELIMITER;
----------------------------------
--INSERTAR PRODUCTOS EMPLEADOS
DELIMITER @@
CREATE PROCEDURE insertarProductoEmpleado(IN MARCA VARCHAR(45),IN MODELO VARCHAR(45),IN PRECIO INT,IN PROMOCION INT,IN FOTO VARCHAR(255))
BEGIN
    INSERT INTO PRODUCTO VALUES(NULL,NULL,MARCA,MODELO,PRECIO,NOW(),PROMOCION,'NO',FOTO,NULL);
END @@
DELIMITER;
   
DELIMITER @@
CREATE PROCEDURE insertarBicicletaEmpleado(IN TIPO_BICICLETA VARCHAR(45),IN ARO INT,IN MARCA VARCHAR(45),IN MODELO VARCHAR(45),IN PRECIO INT,IN PROMOCION INT,IN FOTO VARCHAR(255))
BEGIN
    INSERT INTO PRODUCTO VALUES(TIPO_BICICLETA,ARO,MARCA,MODELO,PRECIO,NOW(),PROMOCION,'NO',FOTO,NULL);
END @@
DELIMITER;
----------------------------------
--INSERTAR PRODUCTOS CLIENTES
DELIMITER @@
CREATE PROCEDURE insertarProductoCliente(IN MARCA VARCHAR(45),IN MODELO VARCHAR(45),IN PRECIO INT,IN PROMOCION INT,IN FOTO VARCHAR(255))
BEGIN
    INSERT INTO PRODUCTO VALUES(NULL,NULL,MARCA,MODELO,PRECIO,NOW(),PROMOCION,'NO',FOTO,NULL);
END @@
DELIMITER;
   
DELIMITER @@
CREATE PROCEDURE insertarBicicletaCliente(IN TIPO_BICICLETA VARCHAR(45),IN ARO INT,IN MARCA VARCHAR(45),IN MODELO VARCHAR(45),IN PRECIO INT,IN PROMOCION INT,IN FOTO VARCHAR(255),IN RUT VARCHAR(45))
BEGIN
    INSERT INTO PRODUCTO VALUES(TIPO_BICICLETA,ARO,MARCA,MODELO,PRECIO,NOW(),PROMOCION,'NO',FOTO,RUT);
END @@
DELIMITER;
----------------------------------
--INSERTAR COTIZACION
DELIMITER @@
CREATE PROCEDURE insertarCotizacion(IN NOMBRE VARCHAR(45),IN APELLIDO VARCHAR(45),IN DESCRIPCION VARCHAR(255),IN TIPO_COTIZACION VARCHAR(45))
BEGIN
    DECLARE V_RUT VARCHAR(45) DEFAULT ' ';
    SELECT RUT INTO V_RUT FROM EMPLEADO WHERE ATENCION=(SELECT MIN(ATENCION) FROM EMPLEADO) LIMIT 1;
    INSERT INTO COTIZACION VALUES(NULL,NOMBRE,APELLIDO,DESCRIPCION,NOW(),TIPO_COTIZACION,NULL,V_RUT);
    UPDATE EMPLEADO SET ATENCION=(ATENCION+1) WHERE RUT=V_RUT;
END @@
DELIMITER;



CALL insertarCotizacion('Juan','Perez','Quiero cotizar la compra de una bicicleta de montaña','Cotizar Bicicleta');
CALL insertarCotizacion('Diego','Gonzales','Quiero cotizar una bicicleta bmx','Cotizar Bicicleta');

SELECT * FROM USUARIO WHERE USER='PDR.PTE-ALTO';
SELECT * FROM EMPLEADO;
SELECT * FROM COTIZACION;
SELECT RUT FROM EMPLEADO WHERE ATENCION=(SELECT MIN(ATENCION) FROM EMPLEADO) LIMIT 1;