SELECT * FROM USUARIO;
SELECT * FROM CLIENTE;
SELECT * FROM EMPLEADO;
SELECT * FROM SUCURSAL;
SELECT * FROM COTIZACION;
SELECT * FROM PRODUCTO;
SELECT * FROM VENTA;
SELECT * FROM PRODUCTO WHERE CLIENTE_RUT IS NULL AND DARBAJA='NO';
DELETE FROM PRODUCTO WHERE IDPRODUCTO=26;
DELETE FROM VENTA;
select rut from CLIENTE where USUARIO_USER='YAN.GON';
select * from producto where idProducto=27;
SELECT * FROM PRODUCTO WHERE TIPOBICICLETA IS NOT NULL;
SELECT * FROM PRODUCTO WHERE CLIENTE_RUT IS NULL ORDER BY IDPRODUCTO DESC LIMIT 12;
SELECT RUT FROM EMPLEADO WHERE USUARIO_USER='PDR.PTE-ALTO';

SELECT * FROM COTIZACION WHERE FECCOTIZACION<DATE_SUB(NOW(),INTERVAL 5 DAY);
SELECT * FROM COTIZACION WHERE FECCOTIZACION<DATE_SUB(NOW(),INTERVAL 5 DAY) AND EMPLEADO_RUT='98765432-1' AND RESPUESTA IS NULL;

DELETE FROM USUARIO WHERE USER='';
DELETE FROM CLIENTE WHERE USUARIO_USER=' ';
DELETE FROM COTIZACION WHERE idCotizacion=15;

UPDATE USUARIO SET ACTIVO='SI' WHERE USER='DIEGO.PTE-ALTO';
UPDATE USUARIO SET tipoUsuario='Cliente' WHERE USER='edd.obr';
UPDATE EMPLEADO SET APELLIDO='RIVERA' WHERE RUT='98765432-1';
SELECT e.RUT,CONCAT(e.NOMBRE,' ',e.apellido),e.CARGO,s.Sucursal,IF(ISNULL(e.ANTICIPO), 0, e.ANTICIPO),e.SUELDO FROM EMPLEADO e 
        JOIN SUCURSAL s ON e.Sucursal_idSucursal=s.idSucursal WHERE e.USUARIO_USER='PDR.PTE-ALTO';

DELIMITER @@
CREATE PROCEDURE insertarUsuario(IN USUARIO VARCHAR(45),
                                 IN PASS VARCHAR(255))
BEGIN
    INSERT INTO USUARIO VALUES(USUARIO,PASS,'CLIENTE');
END @@
DELIMITER ;

DELIMITER @@
CREATE PROCEDURE insertarCliente(IN RUT VARCHAR(45),IN NOMBRE VARCHAR(45),IN APELLIDO VARCHAR(45),
                                 IN DIRECCION VARCHAR(100),IN EMAIL VARCHAR(100),IN TELEFONO VARCHAR(45),IN USUARIO VARCHAR(45))
BEGIN
     INSERT INTO CLIENTE VALUES(RUT,NOMBRE,APELLIDO,DIRECCION,EMAIL,TELEFONO,USUARIO);
END @@
DELIMITER;

CALL insertarUsuario('YAN.GON','YAN123');
CALL insertarCliente('43125970-2','YAN','GONZALES','PSJE YARZO 421','YAN.GONZALES@HOTMAIL.COM','74576543','YAN.GON');

INSERT INTO SUCURSAL VALUES(1,'Puente Alto','Los Aromos 5810','Lunes a Viernes de 8:00 a 20:00');

INSERT INTO USUARIO VALUES('ADMIN','ADMIN','ADMIN','SI');
INSERT INTO USUARIO VALUES('PDR.PTE-ALTO','PDR-123','EMPLEADO');
INSERT INTO USUARIO VALUES('DIEGO.PTE-ALTO','DGO-591','EMPLEADO');
INSERT INTO USUARIO VALUES('Admin','Admin','Admin');

INSERT INTO EMPLEADO VALUES('12345678-9','PEDRO','RAMIREZ','32543252','Las Lluvias 563',350000,'Vendedor',1,NULL,0,'PDR.PTE-ALTO');
INSERT INTO EMPLEADO VALUES('98765432-1','DIEGO','BOLAÑOS','87687431','Nemesio 8476',350000,'Vendedor',1,NULL,4,'DIEGO.PTE-ALTO');

DELIMITER @@
CREATE PROCEDURE insertarRenuncia(IN USUARIO VARCHAR(45))
BEGIN
    UPDATE USUARIO SET ACTIVO='NO' WHERE USER='USUARIO';
    UPDATE EMPLEADO SET FECRENUNCIA=NOW() WHERE USUARIO_USER=USUARIO;
END @@
DELIMITER;

DELIMITER @@
CREATE PROCEDURE validarUsuario(IN USUARIO VARCHAR(45),IN PASS VARCHAR(255))
BEGIN
    SELECT * FROM USUARIO WHERE USER=USUARIO AND PASSWORD=PASS;
END @@
DELIMITER;

CALL insertarRenuncia('DIEGO.PTE-ALTO');
CALL validarUsuario('PDR.PTE-ALTO','PDR-123');
CALL insertarProducto('Montaña',20,'Oparagon','jeep',78000,35,'sadsadsa',NULL,'12345678-9');

UPDATE EMPLEADO SET FECRENUNCIA=NULL WHERE USUARIO_USER='DIEGO.PTE-ALTO';

SELECT * FROM EMPLEADO WHERE FECRENUNCIA IS NULL AND USUARIO_USER='DIEGO.PTE-ALTO';

SELECT u.user,u.tipoUsuario FROM USUARIO u JOIN EMPLEADO e ON u.user=e.Usuario_user 
WHERE user='PDR.PTE-ALTO' AND password='PDR-123' AND e.FECRENUNCIA IS NULL;

UPDATE EMPLEADO SET ANTICIPO='2000' WHERE USUARIO_USER='PDR.PTE-ALTO';
UPDATE PRODUCTO SET DARBAJA='NO' WHERE IDPRODUCTO=29;

SELECT e.RUT,CONCAT(e.NOMBRE,' ',e.apellido),e.CARGO,s.Sucursal,IF(ISNULL(e.ANTICIPO), 0, e.ANTICIPO),e.SUELDO,IF(ISNULL(e.FECRENUNCIA),'ACTIVO',e.FECRENUNCIA) FROM EMPLEADO e 
        JOIN SUCURSAL s ON e.Sucursal_idSucursal=s.idSucursal;

SELECT USUARIO_USER FROM CLIENTE;
SELECT idProducto,nombre,tipoBicicleta,aro,marca,modelo,precio,fecProducto,promocion,stock,darBaja FROM PRODUCTO WHERE EMPLEADO_RUT IS NULL;