--- PROCEDIMIENTOS ALMACENADOS ---
DELIMITER @@
CREATE PROCEDURE LLENAR_REGION()
BEGIN 
    INSERT INTO REGION VALUES(1,'AMERICA');
    INSERT INTO REGION VALUES(2,'EUROPA');
    INSERT INTO REGION VALUES(3,'ASIA');
END @@
DELIMITER ;
----------------------------------
CALL LLENAR_REGION();
SELECT * FROM REGION;
----------------------------------
DELIMITER @@
CREATE PROCEDURE LLENAR_PAIS()
BEGIN 
    INSERT INTO PAIS VALUES(1,'CHILE',1);
    INSERT INTO PAIS VALUES(2,'ESPAÑA',2);
    INSERT INTO PAIS VALUES(3,'CHINA',3);
END @@
DELIMITER ;
----------------------------------
CALL LLENAR_PAIS();
SELECT * FROM PAIS;
----------------------------------
DELIMITER @@
CREATE PROCEDURE LLENAR_UBICACION()
BEGIN 
    INSERT INTO UBICACION VALUES(1,'INDEPENDENCIA','123','SANTIAGO','RM',1);
END @@
DELIMITER ;
----------------------------------
CALL LLENAR_UBICACION();
SELECT * FROM UBICACION;
----------------------------------
INSERT INTO DEPARTAMENTO VALUES(1,'CETECOM',NULL,1);
SELECT * FROM DEPARTAMENTO;
----------------------------------
DELIMITER @@
CREATE PROCEDURE LLENAR_TRABAJOS()
BEGIN 
    INSERT INTO TRABAJOS VALUES(1,'PROGRAMADOR',100000,500000);
    INSERT INTO TRABAJOS VALUES(2,'ANALISTA',500000,800000);
    INSERT INTO TRABAJOS VALUES(3,'INGENIERO',800000,1500000);
    INSERT INTO TRABAJOS VALUES(4,'SENIOR',1500000,3500000);
END @@
DELIMITER ;
----------------------------------
CALL LLENAR_TRABAJOS();
SELECT * FROM TRABAJOS;
---------------------------------- 8/5/2017
DELIMITER @@
CREATE PROCEDURE insertarEmpleado(IN ID INT, IN NOMBRE VARCHAR(45),
                                  IN AP VARCHAR(45), IN EM VARCHAR(45),
                                  IN FO VARCHAR(45), IN FI DATE,
                                  IN SA INT,IN COM DOUBLE, IN IDT INT,
                                  IN IDD INT,IN IDJ INT)
BEGIN
    INSERT INTO EMPLEADOS VALUES(ID,NOMBRE,AP,EM,FO,FI,SA,COM,IDT,IDD,IDJ);
END @@
DELIMITER ;
----------------------------------
CALL insertarEmpleado(1,'JUAN','LOPEZ','JL@LO.COM','225485478','2010/05/05',500000,1,1,1,NULL);
SELECT * FROM EMPLEADOS;
----------------------------------
DELIMITER @@
CREATE PROCEDURE insertarUsuario(IN USUARIO VARCHAR(45),
                                 IN PASS VARCHAR(255))
BEGIN
    INSERT INTO USUARIOS VALUES(USUARIO,PASS);
END @@
DELIMITER ;
----------------------------------
CALL insertarUsuario('JUAN','$2y$10$.tsKtP82XWA0dVEg2AV9SexRmNfMH0hnNQZqttUZsBIeCHrCtbH96');
SELECT * FROM USUARIOS;
----------------------------------
