------ CREACION DE REGIONES ------
DELIMITER //
CREATE PROCEDURE LLENAR_REGION()
BEGIN
    INSERT INTO REGION VALUES(1,'AMERICA');
    INSERT INTO REGION VALUES(2,'EUROPA');
    INSERT INTO REGION VALUES(3,'ASIA');
END //
DELIMITER ;
----------------------------------
CALL LLENAR_REGION();
SELECT * FROM REGION;
----------------------------------
------ CREACION DE PAISES --------
DELIMITER //
CREATE PROCEDURE LLENAR_PAIS()
BEGIN
    INSERT INTO PAIS VALUES(1,'CHILE',1);
    INSERT INTO PAIS VALUES(2,'ARGENTINA',1);
    INSERT INTO PAIS VALUES(3,'BRASIL',1);
    INSERT INTO PAIS VALUES(4,'FRANCIA',2);
    INSERT INTO PAIS VALUES(5,'ALEMANIA',2);
    INSERT INTO PAIS VALUES(6,'ESPAÑA',2);
    INSERT INTO PAIS VALUES(7,'CHINA',3);
    INSERT INTO PAIS VALUES(8,'JAPON',3);
    INSERT INTO PAIS VALUES(9,'COREA DEL NORTE',3);
END //
DELIMITER ;
---------------------------------
CALL LLENAR_PAIS();
SELECT * FROM PAIS;
---------------------------------
DELIMITER //
CREATE PROCEDURE LLENAR_TRABAJO()
BEGIN
    INSERT INTO TRABAJO VALUES(1,'PROGRAMADOR',100000,80000);
    INSERT INTO TRABAJO VALUES(2,'ANALISTA',400000,120000);
    INSERT INTO TRABAJO VALUES(3,'INGENIERO INF.',400000,1600000);
    INSERT INTO TRABAJO VALUES(4,'INGENIERO CIVIL INF.',900000,2800000);
    INSERT INTO TRABAJO VALUES(5,'BANANERO SIMIO',800000,1700000);
END //
DELIMITER ;
---------------------------------
CALL LLENAR_TRABAJO();
SELECT * FROM TRABAJO;
---------------------------------
INSERT INTO UBICACION VALUES(1,'AV. ACME','123456','SANTIAGO','RM',1);
SELECT * FROM UBICACION;
---------------------------------

DELIMITER //
CREATE PROCEDURE LLENAR_DEPTO()
BEGIN
    INSERT INTO DEPARTAMENTO VALUES(1,'CETECOM',1,NULL);
    INSERT INTO DEPARTAMENTO VALUES(2,'RRPP',1,NULL);
    INSERT INTO DEPARTAMENTO VALUES(3,'CAJA',1,NULL);
    INSERT INTO DEPARTAMENTO VALUES(4,'CONTABILIDAD',1,NULL);
END //
DELIMITER ;
---------------------------------
CALL LLENAR_DEPTO();
SELECT * FROM DEPARTAMENTO;
-------------------------------------------------
INSERT INTO EMPLEADOS VALUES(1,'ELESEO','CHANGO','ECHANGO@BANANA.CL','22','2016-1-1',50000,0,NULL,1,2);
SELECT * FROM EMPLEADOS;
-------------------------------------------------

-------------------------------------------------