
DELIMITER @@
CREATE PROCEDURE validarUsuario
(IN USUARIO VARCHAR(45),IN PASS VARCHAR(255))
BEGIN
    SELECT * FROM USUARIO WHERE USER=USUARIO AND PASSWORD=PASS;
END @@ 
DELIMITER @@; 

DELIMITER @@
CREATE PROCEDURE insertarPersona
(IN USUARIO VARCHAR(45),IN PASS VARCHAR(255),IN RUT VARCHAR(11),IN NOMBRE VARCHAR(45),IN APELLIDOP VARCHAR(45), IN APELLIDOM VARCHAR(45),
 IN TIPOPERSONA VARCHAR(45),IN DIRECCION VARCHAR(255),IN TELEFONO VARCHAR(45),IN ESPECIALIDAD VARCHAR(45),IN VALORHORA INT,IN OPCION INT)
BEGIN
    IF(OPCION=1) THEN
      INSERT INTO USUARIO VALUES(USUARIO,PASS,'Cliente','SI');
      INSERT INTO CLIENTE VALUES(RUT,NOMBRE,APELLIDOP,APELLIDOM,NOW(),DIRECCION,TIPOPERSONA,TELEFONO,USUARIO);
    ELSE
     INSERT INTO ABOGADO VALUES(RUT,NOMBRE,APELLIDOP,APELLIDOM,NOW(),ESPECIALIDAD,VALORHORA,'SI');
    END IF;
END @@ 
DELIMITER @@;

DELIMITER @@
CREATE PROCEDURE insertarAtencion
(IN RUTCLI VARCHAR(45),IN RUTABO VARCHAR(45),IN FECHA DATETIME,IN ESTADO VARCHAR(45))
BEGIN
  INSERT INTO ATENCION VALUES(NULL,RUTCLI,RUTABO,FECHA,ESTADO);
END @@
DELIMITER @@;

DELIMITER @@
CREATE PROCEDURE listarAtenciones()
BEGIN
  SELECT a.CLIENTE_RUT,CONCAT(c.NOMBRE,' ',c.APELLIDOP,' ',c.APELLIDOM),
       a.ABOGADO_RUT,CONCAT(ab.NOMBRE,' ',ab.APELLIDOP,' ',ab.APELLIDOM),DATE_FORMAT(a.FECHA,'%d-%m-%Y %H:%i'),a.ESTADO,a.IDATENCION
       FROM ATENCION a JOIN CLIENTE c ON a.CLIENTE_RUT = c.RUT JOIN ABOGADO ab ON a.ABOGADO_RUT = ab.RUT;
END @@
DELIMITER @@;

DELIMITER @@
CREATE PROCEDURE listarClientes()
BEGIN
  SELECT c.RUT,CONCAT(c.NOMBRE,' ',c.APELLIDOP,' ',c.APELLIDOM),DATE_FORMAT(c.FECINCORPORACION,'%d-%m-%Y'),c.TIPOPERSONA,c.DIRECCION,
       c.TELEFONO,c.USUARIOS_USER FROM CLIENTE c JOIN USUARIO u ON c.usuarios_user=u.user WHERE u.ACTIVO='SI';
END @@
DELIMITER @@;

DELIMITER @@
CREATE PROCEDURE listarAbogados()
BEGIN
  SELECT RUT,CONCAT(NOMBRE,' ',APELLIDOP,' ',APELLIDOM),DATE_FORMAT(FECCONTRATACION,'%d-%m-%Y'),ESPECIALIDAD,VALORHORA,ACTIVO
        FROM ABOGADO;
END @@
DELIMITER @@;

DELIMITER @@
CREATE PROCEDURE estadisticasClientes(IN OPCION INT)
BEGIN
  IF(OPCION=1)THEN
   SELECT CONCAT(NOMBRE,' ',APELLIDOP,' ',APELLIDOM),TIMESTAMPDIFF(MONTH, FECINCORPORACION, NOW()) FROM CLIENTE GROUP BY NOMBRE;
  ELSEIF(OPCION=2) THEN
   SELECT TIPOPERSONA,COUNT(*) FROM CLIENTE GROUP BY TIPOPERSONA;
  ELSEIF(OPCION=3) THEN
   SELECT CONCAT(NOMBRE,' ',APELLIDOP,' ',APELLIDOM),COUNT(*) FROM CLIENTE c LEFT OUTER JOIN ATENCION a ON(c.RUT=a.CLIENTE_RUT) GROUP BY NOMBRE;
  END IF;
END @@
DELIMITER @@;

DELIMITER @@
CREATE PROCEDURE depedirPersona
(IN USUARIO INT,IN RUTABOGADO INT,IN OPCION INT)
BEGIN
    IF(OPCION=1) THEN
      UPDATE USUARIO SET ACTIVO='NO' WHERE USER=USUARIO;
    ELSE
     UPDATE ABOGADO SET ACTIVO='NO' WHERE RUT=RUTABOGADO;
    END IF;
END @@ 
DELIMITER @@;

SELECT a.CLIENTE_RUT,CONCAT(c.NOMBRE,' ',c.APELLIDOP,' ',c.APELLIDOM),
       a.ABOGADO_RUT,CONCAT(ab.NOMBRE,' ',ab.APELLIDOP,' ',ab.APELLIDOM),DATE_FORMAT(a.FECHA,'%d-%m-%Y %H:%i'),a.ESTADO
       FROM ATENCION a JOIN CLIENTE c ON a.CLIENTE_RUT = c.RUT JOIN ABOGADO ab ON a.ABOGADO_RUT = ab.RUT;

SELECT c.RUT,CONCAT(c.NOMBRE,' ',c.APELLIDOP,' ',c.APELLIDOM),DATE_FORMAT(c.FECINCORPORACION,'%d-%m-%Y'),c.TIPOPERSONA,c.DIRECCION,
       c.TELEFONO,c.USUARIOS_USER FROM CLIENTE c JOIN USUARIO u ON c.usuarios_user=u.user WHERE u.ACTIVO='SI';

SELECT RUT,CONCAT(NOMBRE,' ',APELLIDOP,' ',APELLIDOM),DATE_FORMAT(FECCONTRATACION,'%d-%m-%Y'),ESPECIALIDAD,VALORHORA,ACTIVO
        FROM ABOGADO;

SELECT CONCAT(NOMBRE,' ',APELLIDOP,' ',APELLIDOM),TIMESTAMPDIFF(MONTH, FECINCORPORACION, NOW()) FROM CLIENTE GROUP BY NOMBRE;
SELECT TIPOPERSONA,COUNT(*) FROM CLIENTE GROUP BY TIPOPERSONA;
SELECT c.NOMBRE,COUNT(*) FROM CLIENTE c LEFT OUTER JOIN ATENCION a ON(c.RUT=a.CLIENTE_RUT) GROUP BY NOMBRE;

SELECT * FROM USUARIO;
SELECT * FROM CLIENTE;
SELECT * FROM ABOGADO;
SELECT * FROM ATENCION;
SELECT COUNT(CLIENTE_RUT) FROM ATENCION;

DELETE FROM ATENCION;
DELETE FROM ABOGADO;
DELETE FROM CLIENTE;
DELETE FROM USUARIO WHERE TIPOUSUARIO='Cliente';

UPDATE CLIENTE SET TIPOPERSONA='Natural' WHERE RUT='';
call insertarAtencion('19.584.598-0','122321-2','2017-07-01 11:00','Agendada');
call estadisticasClientes(1);
INSERT INTO USUARIO VALUES ('admin','admin','Administrador','SI');

call insertarPersona('Edd2','$2y$10$FfUfkJWLb9Pv0StrxWaji.hA2zLJnFuSA8j02vkiy7dmTl/3GJZNu','19.584.598-0','Eduardo','Obreque','Obreque','81I5pdbIyxQiYjHqYBgCTeQPdjwCYFG+OH0EKl45+JA=','Natural','957424232',NULL,NULL,1);

SELECT a.CLIENTE_RUT,CONCAT(c.NOMBRE,' ',c.APELLIDOP,' ',c.APELLIDOM),
        a.ABOGADO_RUT,CONCAT(ab.NOMBRE,' ',ab.APELLIDOP,' ',ab.APELLIDOM),DATE_FORMAT(a.FECHA,'%d-%m-%Y %H:%i'),a.ESTADO,a.IDATENCION
        FROM ATENCION a JOIN CLIENTE c ON a.CLIENTE_RUT = c.RUT JOIN ABOGADO ab ON a.ABOGADO_RUT = ab.RUT WHERE a.CLIENTE_RUT='19.584.598-0' ;

SELECT * FROM ATENCION WHERE FECHA<DATE_ADD(NOW(),INTERVAL 1 DAY) AND FECHA>NOW() AND ESTADO<>'Confirmada' AND ESTADO<>'Perdida' AND ESTADO<>'Realizada' AND ESTADO<>'Anulada';

SELECT a.cliente_rut,CONCAT(c.NOMBRE,' ',c.APELLIDOP,' ',c.APELLIDOM),a.abogado_rut,CONCAT(ab.NOMBRE,' ',ab.APELLIDOP,' ',ab.APELLIDOM),
a.fecha,a.estado,a.idAtencion
FROM ATENCION a JOIN CLIENTE c ON a.cliente_rut=c.rut JOIN ABOGADO ab ON a.abogado_rut=ab.rut
WHERE TO_DAYS(fecha)-TO_DAYS(DATE_ADD(NOW(),INTERVAL 2 DAY))=0 AND ESTADO='Agendada' ORDER BY a.fecha DESC;
SELECT a.cliente_rut,CONCAT(c.NOMBRE,' ',c.APELLIDOP,' ',c.APELLIDOM),a.abogado_rut,CONCAT(ab.NOMBRE,' ',ab.APELLIDOP,' ',ab.APELLIDOM),
a.fecha,a.estado,a.idAtencion
FROM ATENCION a JOIN CLIENTE c ON a.cliente_rut=c.rut JOIN ABOGADO ab ON a.abogado_rut=ab.rut
WHERE TO_DAYS(fecha)-TO_DAYS(DATE_ADD(NOW(),INTERVAL 2 DAY))=0 AND ESTADO<>'Anulada' AND ESTADO<>'Realizada' ORDER BY a.fecha DESC;

SELECT fecha,TO_DAYS(fecha) - TO_DAYS(DATE_ADD(NOW(),INTERVAL 2 DAY)) FROM ATENCION;
SELECT fecha,TO_DAYS(fecha) - TO_DAYS(DATE_ADD(NOW(),INTERVAL 1 DAY)) FROM ATENCION;

UPDATE ATENCION SET FECHA='2017-07-12 12:00' WHERE IDATENCION=28;
UPDATE ATENCION SET ESTADO='Agendada' WHERE IDATENCION=4;
UPDATE ATENCION SET ESTADO='Agendada',FECHA='2017-07-03 12:00' WHERE IDATENCION=20;